repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
        exclude: \.c$
    -   id: debug-statements
    -   id: detect-private-key
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
-   repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
    -   id: flake8
        args: ['--max-line-length=131', '--ignore=E203,W503,E501']
-   repo: https://github.com/PyCQA/autoflake
    rev: v2.2.0  # Use the latest stable version
    hooks:
    -   id: autoflake
        args: ["--remove-all-unused-imports", "--remove-unused-variables", "--in-place"]
